service: NestServerlessFunction

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-stage-manager
provider:
  name: aws
  tracing:
    apiGateway: false
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2


package:
  exclude:
    - .gitignore
    - README.md
    - serverless.yml
    - nest-cli.json
    - .prettierrc
  excludeDevDependencies: true
  individually: true

functions:
  main:
    handler: src/main.handler


custom:
  stages:
    - dev
    - test
    - acc
    - prod


